name: pressure_diary_fresh
description: Pressure diary (Flutter/Dart, Hive, fl_chart)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Локализации (НУЖНО быть внутри dependencies!)
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2

  # UI
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.8

  # Хранилище и графики
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.68.0

  # Системные вещи
  url_launcher: ^6.3.1
  path_provider: ^2.1.4
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  flutter_timezone: ^4.1.1
  shared_preferences: ^2.3.2
  share_plus: ^9.0.0
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
